name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */6 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: steamcmd/steamcmd

    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: true
          fetch-depth: 0

      - uses: actions/cache@main
        with:
          key: dst
          path: /home/runner/dst

      - name: Download Dst Server
        run: steamcmd +force_install_dir /home/runner/dst +login anonymous +app_update 343050 validate +quit

      - name: Check Update
        run: |
          [ $(git log --format=%B --max-count=1) = $(cat /home/runner/dst/version.txt) ] || \
          echo "version=$(cat /home/runner/dst/version.txt)" >> $GITHUB_ENV

      - name: Unzip
        if: ${{ env.version }}
        run: unzip -o /home/runner/dst/data/databundles/scripts.zip

      - name: Push Changes
        if: ${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          MESSAGE: ${{ env.version }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m $MESSAGE
          git push
